name: Deploy to EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    
    - name: Create SSH key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
    
    - name: Set environment variables
      run: |
        if [[ $GITHUB_REF == "refs/heads/main" ]]; then
          echo "Setting up production environment"
          # Create .env file with production variables
          cat << EOF > .env
          PORT=${{ secrets.PROD_PORT }}
          URL=${{ secrets.PROD_URL }}
          URI=${{ secrets.PROD_URI }}
          MYSQL_HOST=${{ secrets.PROD_MYSQL_HOST }}
          MYSQL_USER=${{ secrets.PROD_MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.PROD_MYSQL_PASSWORD }}
          MYSQL_PORT=${{ secrets.PROD_MYSQL_PORT }}
          MYSQL_DATABASE=${{ secrets.PROD_MYSQL_DATABASE }}
          NODEMAILER_HOST=${{ secrets.PROD_NODEMAILER_HOST }}
          NODEMAILER_POST=${{ secrets.PROD_NODEMAILER_POST }}
          NODEMAILER_AUTH_USER=${{ secrets.PROD_NODEMAILER_AUTH_USER }}
          NODEMAILER_AUTH_PASS=${{ secrets.PROD_NODEMAILER_AUTH_PASS }}
          EOF
        else
          echo "Setting up development environment"
          # Create .env file with development variables
          cat << EOF > .env
          PORT=${{ secrets.DEV_PORT }}
          URL=${{ secrets.DEV_URL }}
          URI=${{ secrets.DEV_URI }}
          MYSQL_HOST=${{ secrets.DEV_MYSQL_HOST }}
          MYSQL_USER=${{ secrets.DEV_MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.DEV_MYSQL_PASSWORD }}
          MYSQL_PORT=${{ secrets.DEV_MYSQL_PORT }}
          MYSQL_DATABASE=${{ secrets.DEV_MYSQL_DATABASE }}
          NODEMAILER_HOST=${{ secrets.DEV_NODEMAILER_HOST }}
          NODEMAILER_POST=${{ secrets.DEV_NODEMAILER_POST }}
          NODEMAILER_AUTH_USER=${{ secrets.DEV_NODEMAILER_AUTH_USER }}
          NODEMAILER_AUTH_PASS=${{ secrets.DEV_NODEMAILER_AUTH_PASS }}
          EOF
        fi
    
    - name: Deploy to EC2
      run: |
        # Copy files to EC2
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/deploy_key" \
          --exclude '.git' \
          --exclude '.github' \
          --exclude 'node_modules' \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/
        
        # Execute deployment commands on EC2
        ssh -i ~/.ssh/deploy_key ubuntu@${{ secrets.EC2_HOST }} '
          cd /home/ubuntu/app
          npm install  # <-- Installs dependencies
          sudo systemctl daemon-reload
          sudo systemctl enable giftcard-giveaway.service
          sudo systemctl restart giftcard-giveaway.service # <-- Changed to restart
          sudo systemctl restart caddy.service
        '